// src/data/textOptions.js

export const FontsDatabase = [
  { name: "Arial", fontFamily: "Arial, sans-serif" },
  { name: "Courier New", fontFamily: "'Courier New', monospace" },
  { name: "Times New Roman", fontFamily: "'Times New Roman', serif" },
  { name: "Verdana", fontFamily: "Verdana, sans-serif" },
  { name: "Georgia", fontFamily: "Georgia, serif" },
  { name: "Dancing Script", fontFamily: "'Dancing Script', cursive" },
  { name: "Badeen Display", fontFamily: "'Badeen Display', cursive" },
];

export const textColors = [
  { name: "Black", value: "#000000" },
  { name: "Red", value: "#FF0000" },
  { name: "Blue", value: "#0000FF" },
  { name: "Green", value: "#00FF00" },
  { name: "Yellow", value: "#FFFF00" },
  { name: "White", value: "#FFFFFF" },
  { name: "Gray", value: "#808080" },
  { name: "Pink", value: "#FFC0CB" },
  { name: "Purple", value: "#800080" },
  { name: "Orange", value: "#FFA500" },
  { name: "Brown", value: "#A52A2A" },
  { name: "Cyan", value: "#00FFFF" },
  { name: "Magenta", value: "#FF00FF" },
  { name: "Lime", value: "#00FF00" },
  { name: "Teal", value: "#008080" },
  { name: "Navy", value: "#000080" },
  { name: "Maroon", value: "#800000" },
  { name: "Olive", value: "#808000" },
  { name: "Silver", value: "#C0C0C0" },
  { name: "Gold", value: "#FFD700" },
  { name: "Coral", value: "#FF7F50" },
  { name: "Indigo", value: "#4B0082" },
  { name: "Lavender", value: "#E6E6FA" },
  { name: "Mint", value: "#98FF98" },
  { name: "Peach", value: "#FFDAB9" },
  { name: "Salmon", value: "#FA8072" },
  { name: "Khaki", value: "#F0E68C" },
  { name: "Plum", value: "#DDA0DD" },
  { name: "Turquoise", value: "#40E0D0" },
  { name: "Chocolate", value: "#D2691E" },
  { name: "Crimson", value: "#DC143C" },
  { name: "DarkGreen", value: "#006400" },
  { name: "DarkBlue", value: "#00008B" },
  { name: "DarkRed", value: "#8B0000" },
  { name: "DarkOrange", value: "#FF8C00" },
  { name: "DarkMagenta", value: "#8B008B" },
  { name: "DarkCyan", value: "#008B8B" },
  { name: "DarkGray", value: "#A9A9A9" },
  { name: "LightGray", value: "#D3D3D3" },
  { name: "LightPink", value: "#FFB6C1" },
  { name: "LightBlue", value: "#ADD8E6" },
  { name: "LightGreen", value: "#90EE90" },
];

export const outlineColors = [
  { name: "None", value: "none" },
  { name: "Red", value: "#FF0000" },
  { name: "Blue", value: "#0000FF" },
  { name: "Green", value: "#00FF00" },
  { name: "Yellow", value: "#FFFF00" },
  { name: "White", value: "#FFFFFF" },
  { name: "Gray", value: "#808080" },
  { name: "Pink", value: "#FFC0CB" },
  { name: "Purple", value: "#800080" },
  { name: "Orange", value: "#FFA500" },
  { name: "Brown", value: "#A52A2A" },
  { name: "Cyan", value: "#00FFFF" },
  { name: "Magenta", value: "#FF00FF" },
  { name: "Lime", value: "#00FF00" },
  { name: "Teal", value: "#008080" },
  { name: "Navy", value: "#000080" },
  { name: "Maroon", value: "#800000" },
  { name: "Olive", value: "#808000" },
  { name: "Silver", value: "#C0C0C0" },
  { name: "Gold", value: "#FFD700" },
  { name: "Coral", value: "#FF7F50" },
  { name: "Indigo", value: "#4B0082" },
  { name: "Lavender", value: "#E6E6FA" },
  { name: "Mint", value: "#98FF98" },
  { name: "Peach", value: "#FFDAB9" },
  { name: "Salmon", value: "#FA8072" },
  { name: "Khaki", value: "#F0E68C" },
  { name: "Plum", value: "#DDA0DD" },
  { name: "Turquoise", value: "#40E0D0" },
  { name: "Chocolate", value: "#D2691E" },
  { name: "Crimson", value: "#DC143C" },
  { name: "DarkGreen", value: "#006400" },
  { name: "DarkBlue", value: "#00008B" },
  { name: "DarkRed", value: "#8B0000" },
  { name: "DarkOrange", value: "#FF8C00" },
  { name: "DarkMagenta", value: "#8B008B" },
  { name: "DarkCyan", value: "#008B8B" },
  { name: "DarkGray", value: "#A9A9A9" },
  { name: "LightGray", value: "#D3D3D3" },
  { name: "LightPink", value: "#FFB6C1" },
  { name: "LightBlue", value: "#ADD8E6" },
  { name: "LightGreen", value: "#90EE90" },
];
